### ISSUE TITLE
Building Block - Profile

### ISSUE THREAD

**Issue by mtorrison** [rokwire/rokwire-building-blocks-api#10]
### Description
As a user, I need to have a user profile in the system, which can be accessed and updated as needed and shared with microservices apps based on my preferences, so that my interactions with these microservice apps will be richer in experience.

Some sections of the user profile will be provided by the identity provider (E.g. University, Google, etc.), while some sections will be provided by the user. Tasks under this epic could include requirements gathering and analysis, developing prototypes for the service endpoints, getting feedback, developing the actual service endpoints, deploying them, etc.

### Acceptance Criteria (SAVVI)
Profile building block source code is available in a repository with supporting documents like README, CHANGELOG, LICENSE, Contributors License Agreement, etc. and the service is developed, tested, and running in production for the SAVVI project according to their [product requirements](https://opensource.ncsa.illinois.edu/confluence/display/SCCI/Profile+Building+Block) and built in an extensible manner for future project development.

### Acceptance Criteria (Rokwire)
Profile building block source code is available in a repository with supporting documents like README, CHANGELOG, LICENSE, Contributors License Agreement, etc. and the service is developed, tested, and running in production in a scalable manner according to Rokwire product requirements.

**Comment by sandeep-ps** [comment]
Closing epic as relevant tasks are complete.
