### ISSUE TITLE
[BUG] API base URL added from the Contributions BB not getting displayed in the Catalog Contribution page

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/rokwire-building-blocks-api#1047]
**Describe the bug**
When adding an API base URL from the Contributions BB, it's getting displayed as None.

**To Reproduce**
1. Add Contribution from the Contributions BB using Postman
2. View Contributions details from the Catalog
3. Click Edit Contribution
4. See that API Base URL is "None" in the Catalog details

**Expected behavior**
API Base URL in the Catalog needs to have the value added from Postman.

**Screenshots**
<img width="506" alt="image" src="https://user-images.githubusercontent.com/4306604/206720688-ff59a613-b7c3-4b91-9526-be161cfdfc40.png">
E.g. the above screenshot is from the random Capability "Gorgeous Steel Mouse 774". You should have access to it.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Develop

**Additional context**

**Comment by minump** [comment]
The POST and PUT json data contains the value of ApiBaseUrl field. Somehow in GET /contributions/id it is "None". Trying to figure out why

**Comment by sandeep-ps** [comment]
Closing this as complete. Thanks.
