### ISSUE TITLE
[BUG] Multiple admins in the Contribution admins field not getting displayed and saved properly

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/rokwire-building-blocks-api#1050]
**Describe the bug**
If there are multiple admins in the Contribution admins field, it's not getting saved properly during multiple edits. 

**To Reproduce**
1. Create a Contribution with more than one admin in the list 
2. Click the Edit Contribution button
3. See that commas are not present in the Contribution admins field.
4. Make some changes other than the Contribution admins field.
5. Check the Contribution data from Postman
6. See that there are blank spaces in the list.

**Expected behavior**
Commas should appear in the submission form as the comma separated list of admins GitHub usernames should get saved without the extra spaces in the database.

**Screenshots**
Catalog screesht showing missing commas in the admin users list:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/4306604/206779639-a704e2b6-cade-4cb3-9c46-8fcef11ae49d.png">

Postman response screenshot showing blank space in the list
<img width="195" alt="image" src="https://user-images.githubusercontent.com/4306604/206779448-545b6cc4-9713-4aa9-a33c-ad058acf09a0.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: current develop

**Additional context**

**Comment by minump** [comment]
merged to release1.17.0 branch.Closing this issue.
