### ISSUE TITLE
[BUG] Select Contribution Type buttons not displayed properly in catalog

### ISSUE THREAD

**Issue by minump** [rokwire/rokwire-building-blocks-api#1054]
**Describe the bug**
Select Contribution Type (Add a Capability and Add a Talent buttons) are overlapping with other fields/ div in catalog.
This happens when the "Select contribution type" div is moved while adding a new capability, and the already rendered page has new divs / fields added because of clicking IsOpenSource radio button / adding new env variables. 
This happens in both create and edit page

**To Reproduce**
1. Create a contribution with a "capabilityA" with IsOpenSource radio buttons left blank.
2. Go to edit page for that contribution
3. Click "Add a Capability"
4. In the previous "capabilityA", click radio button "yes" for IsOpenSource.
5. See the "Select contribution type" div overlapping with nav-breadcrumbs.

**Expected behavior**
No overlapping divs and displayed properly.

**Screenshots**
![Screen Shot 2022-12-15 at 10 33 32 AM](https://user-images.githubusercontent.com/22112888/207917610-d97a912e-a4cf-4746-91a7-67feb133fe92.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
This issue can be seen in other cases too. Try different settings on edit / create page and change "Add environment variables" and "IsOpenSource" values. See overlap of divs.

**Comment by sandeep-ps** [comment]
Could this be a browser cache issue? I'm not seeing this overlap in Chrome, though some horizontal space between the buttons and the navigation breadcrumbs could be added later. Even if this is reproducible, I don't think it should affect the ongoing release, as it seems to happen only with a very particular flow of user actions. As in, it does not seem to hinder adding a single/simple Contribution with a Capability and Talent. Thanks.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/4306604/208148351-a18074aa-51b2-4c84-9495-702cdcf01c48.png">
