### ISSUE TITLE
Building Block - Events

### ISSUE THREAD

**Issue by mtorrison** [rokwire/rokwire-building-blocks-api#11]
### Description
As an admin user, I need to manage events in the Rokwire platform. The tasks under this could include, creating, reading, updating, and deleting events. 

As a regular user, I need to view events that are relevant to me. The tasks under this could include getting events based on user role (student, staff, faculty, public, etc.), specific date ranges (today, tomorrow, next week, etc.), my present location details (finding nearby events, my interests (sports, music, etc.).

### Acceptance Criteria (SAVVI)
Events building block source code is available in a repository with supporting documents like README, CHANGELOG, LICENSE, Contributors License Agreement, etc. and the building block is developed, tested, and running in production for the SAVVI project according to their [product requirements](https://opensource.ncsa.illinois.edu/confluence/display/SCCI/Events+Building+Block) and built in an extensible manner for future project development.

### Acceptance Criteria (Rokwire)
Events building block source code is available in a repository with supporting documents like README, CHANGELOG, LICENSE, Contributors License Agreement, etc. and the building block is developed, tested, and running in production in a scalable manner according to Rokwire product requirements.

**Comment by sandeep-ps** [comment]
Closing this Epic as it is complete.
