### ISSUE TITLE
Building Block - Logging

### ISSUE THREAD

**Issue by mtorrison** [rokwire/rokwire-building-blocks-api#12]
### Description
1. As the mobile app client (software), I need to log user activities in a database in a fast manner so that it can be used for getting inferences about app usage in the future. The logging building block should be configurable so that the format and the data that gets logged should be easily changeable.

2. As the Rokwire platform (software), different building blocks need to log events in a database, so that it can be used to track errors and other issues as identified.

3. As an external service provider (software), I need a way to send logs to Rokwire Platform so that it can be used for getting inferences about the external service provider usage in the future. This can be the external service provider pushing logs from their system or the Platform pulling logs from them.

### Acceptance Criteria (SAVVI)
Logging building block source code is available in a repository with supporting documents like README, CHANGELOG, LICENSE, Contributors License Agreement, etc. and the building block is developed, tested, and running in production in a scalable manner according to SAVVI [product requirements](https://opensource.ncsa.illinois.edu/confluence/display/SCCI/Logging+Building+Block). This building block might use a specialized database that's used for logging purposes.

**Comment by sandeep-ps** [comment]
Closing the epic as the relevant tasks are complete.
