### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by mtorrison** [rokwire/rokwire-building-blocks-api#13]
### Description
As a developer, I need to have a database schema designed and implemented in a database so that I can efficiently store data for the Rokwire Platform.

Task breakdown to include FERPA consideration (as appropriate for MVP), identifying the specific database technology that will be used, documenting the data schema, building the database, etc.

### Requirements Document
https://opensource.ncsa.illinois.edu/confluence/display/SCCI/Database

### Acceptance Criteria (SAVVI)
The database schema is documented and available in a place for future reference. The actual database is implemented based on the documented schema. This is with an understanding that since we decided to use a NoSQL database for storing data, the schema can change in the future and there is no strict structure in place. The goal of this epic is to have a high-level understanding of the overall schema and the implementation of it within a database. Regarding implementation, highly sensitive data should be definitely encrypted at rest and transfer. If there is not much performance reduction, all data needs to be encrypted at rest and transfer.

**Comment by sandeep-ps** [comment]
Closing this Epic as it is complete.
