### ISSUE TITLE
Orchestration

### ISSUE THREAD

**Issue by mtorrison** [rokwire/rokwire-building-blocks-api#14]
### Description 
As an admin, I need to be able to run different platform building blocks as containers and orchestrate their provisioning, scaling and interactions so that the building blocks are available for consumption at a production grade. The tasks under this epic could include understanding requirements in terms of the usage of the building blocks when in production, using Kubernetes for orchestration, comparing existing options for deploying Kubernetes available via AWS, and deploying the platform building blocks in a Kubernetes cluster in AWS.

### Requirements Document
https://opensource.ncsa.illinois.edu/confluence/display/SCCI/Orchestration

### Acceptance Criteria (SAVVI)
All the platform building blocks are running inside a Kubernetes cluster in AWS and the redundancy and scale of the system has been tested to meet the expected usage of the SAVVI project app.

**Comment by sandeep-ps** [comment]
Closing as orchestration is being done by the operations team.
