### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by mtorrison** [rokwire/rokwire-building-blocks-api#17]
### Description
As a DevOps person, I need to have Continuous Integration / Continuous Deployment (CI/CD) setup in the source code repositories so as to ensure that the code changes build fine. This will help developers to ensure that their changes are building properly before issuing a pull request. This will also help the Software Quality Assurance team to have an automated workflow in place for testing.

### Acceptance Criteria (SAVVI)
For SAVVI mobile app (Illini), automatic building of the source code and deployment of the built packages to Play Store (Google) and App Store (Apple) projects is in place. These projects will be **closed beta** and will notify QA team when a new version gets deployed.

**Comment by sandeep-ps** [comment]
Closing as this is not currently active.
