### ISSUE TITLE
[EPIC] Performance improvements, round 1

### ISSUE THREAD

**Issue by sbutler** [rokwire/rokwire-building-blocks-api#249]
Performance items discovered during some runs with Apache bench.

- Because we're a DB heavy app, using gunicorn gevent worker class gives us bunch better simultaneous requests. This was also a suggestion by the AWS Techs.
- Remove coding practices that disabled MongoClient pools. The Flash `g` context only lives for an request lifetime, so storing the client in there does not utilize connection pools. Also, `close` was being called at the end of each request anyway. Refactor to keep the client around for a process lifetime as pymongo recommends.
- Profiles block was using the flask server, which is not appropriate for production traffic. Switch to using gunicorn like the rest of the blocks.
- Events block was using regex to match categories. Be more intellegent about it and enable it to use indexes by constructing a better query.

**Comment by sandeep-ps** [comment]
Closing this.
