### ISSUE TITLE
[TASK] deployed events building block develop branch.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/rokwire-building-blocks-api#385]
### Description
refactor branch has been merged to develop, thus we need to build and deploy events building block to api-dev.

### Acceptance Criteria
functionalities should work.

**Comment by bingzhang** [comment]
mark it as epic, since we will do it periodically.

**Comment by sandeep-ps** [comment]
As the basic refactoring for Events Building Block is complete, I think this epic can be closed. Thanks.

**Comment by sandeep-ps** [comment]
Closing this epic based on the previous comment. Thanks.
