### ISSUE TITLE
[BUG] Pii data in Splunk

### ISSUE THREAD

**Issue by yoonlees** [rokwire/rokwire-building-blocks-api#556]
**Describe the bug**
Ryan Thomas found the pii data from Splunk and we don't want ingest the pii. 

{ [-] 
    address: null 
    birthYear: null 
    country: null 
    creationDate: 2020-08-16T23:31:07.407Z 
    documentType: null 
    email: xxxx@illinois.edu 
    ep_building_block: profile_building_block 
    ep_method: PUT 
    ep_name: PII 
    firstname: xxxxx 
    healthcareProviderIDs: null 
    homeCounty: null 
    imageUrl: null 
    lastModifiedDate: 2020-09-15T19:55:08.521Z 
    lastname: xxxx 
    middlename: xxxx 
    netid: xxxx 
    phone: null 
    photoImageBase64: null 
    pid: 23e24f77-213f-46f2-8f5a-646bc58ce00c 
    state: null 
    testResultsConsent: null 
    uin: xxxxxxxxx 
    username: null 
    uuid: [ [-] 
     4350b7b0-b7db-4d5f-ae0d-10ceab59bf4b
     c0d8f9ea-218e-4d0f-960c-2bd81be3009a 
   ] 
    workCounty: null 
    zipCode: null  
}

**To Reproduce**
1. Go to Rokwire Team - Illinois Splunk app  
2. Search index=apps-rokwire_illinois sourcetype=illinois:rokwire:profile 23e24f77-213f-46f2-8f5a-646bc58ce00c

**Comment by sandeep-ps** [comment]
@ywkim312, as it looks like currently PII data is not needed in Splunk, let's discuss about reducing the log data for PII endpoints.

**Comment by ywkim312** [comment]
Ok.

**Comment by sandeep-ps** [comment]
@yoonlees, would it help if we print only the PID for future reference as a string or will it affect how Splunk parses the log data? Could you please confirm this with Ryan? Please see PR #557 for reference.

**Comment by wryanthomas** [comment]
It is unclear to me what the requirements are. Yoon has a clearer understanding. My understanding is the user_uuid (or as it is sometimes in the log data, uuid or uid) is the string we need in Rokwire ... and not things like netid, email, phone, address. Whether or not we should have pid, I cannot say and defer to Yoon. I must say that it would be convenient to have a value that would allow us to relate multiple uuids to a "person" entity. (Is pid such a thing?) But I defer to Yoon's guidance.

**Comment by sandeep-ps** [comment]
Yes, PID links multiple UUIDs into one. @yoonlees, could you please let us know what feature change is needed here? Also, if PID is needed, would a string log work (e.g. `"PID GET <PID value>"`) or does the PID needs to be in a JSON string like `"PID GET {\"pid\": \"<PID Value>\"}"`.

**Comment by yoonlees** [comment]
@sandeep-ps Ryan and I had a good discussion about this and we want to keep PII and its related UUIDs and remove all other personal data. In Splunk Ryan is planning to go extra and obfuscated those IDs. 

Also don't bother to change the JSON format to other format. See my example: 
{
  "pid": "xyz",
  "uuid": [ 
    "4350b", 
    "c0d8f"
  ]
}

**Comment by ywkim312** [comment]
Ok, I will work on it tomorrow morning.

**Comment by sandeep-ps** [comment]
Thanks @yoonlees and @ywkim312.

**Comment by wryanthomas** [comment]
Just to clarify. Yoon wrote "keep PII and its related UUIDs".  But, I believe he meant "keep pid and its related uuids".  I'm not planning to do any further obfuscation of the pid or uuid values.  I consider them sufficiently obfuscated. So the "PII" that we want to remove from the logs are UIN, netid, phone, email, address.

Yoon, I hope I'm representing your/our intent.

**Comment by sandeep-ps** [comment]
@wryanthomas, this fix has been deployed to production. Please feel free to reopen or create new issue if the issue is not resolved.
