### ISSUE TITLE
[BUG] creationDate time format inconsistent (sometimes wrong) in profile data

### ISSUE THREAD

**Issue by wryanthomas** [rokwire/rokwire-building-blocks-api#566]
**Describe the bug**
The creationDate time values in profile logs, when ep_name = Profile, are using the wrong time format. (Time format is correct when ep_name = PII.) The result is inconsistent creationDate time values. Here is a sample of a uuid with two creationDate timestamps in profile data:

Profile | 2020/08/18T16:23:52
PII | 2020-08-18T16:24:46.407Z

The preferred format is the ISO 8601-compatible version, the one being used where ep_name = PII:
2020-08-18T16:24:46.407Z

**To Reproduce**
I'm not sure what produces the error, I can only see the evidence of it in the logs.

To see the issue...
Search logs, aggregate by uuid (user_uuid) and list creationDate.

In Splunk, use the following command from Rokwire Team app. (Has dependency of user_uuid field extraction/eval available in the app.)  If you use 'verbose' mode, you can then view the events individually.

```
index=apps-rokwire_illinois sourcetype="illinois:rokwire:profile"
| stats list(ep_name) AS ep_name list(creationDate) AS creationDate by user_uuid
| eval ep_name = mvdedup(ep_name)
| eval creationDate = mvdedup(creationDate)
```

**Expected behavior**
timestamps should always be written with the same time format in the profile logs (preferably in ISO 8601-compliant time format).

**Comment by ywkim312** [comment]
I can fix the code for profiles but that would not change the time format that has already been recorded. Should we fix all the time format of the all profiles records in the existing db?

**Comment by ywkim312** [comment]
Anyway, I fixed the issue and made a PR so after this fix get deployed, the Profiles record will have the same timestamp format as PII.

**Comment by sandeep-ps** [comment]
Thanks @ywkim312. 

I would recommend fixing this for future cases, If there are no issues with Slunk logs/dashboards.
