### ISSUE TITLE
[FEATURE] Add method to Auth Library to get Rokwire groups that the user is part of

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/rokwire-building-blocks-api#600]
**Is your feature request related to a problem? Please describe.**
For authorizing whether a user has access to a private group event, we need to know which groups the user is part of.

**Describe the solution you'd like**
Please add a method to Auth Library that uses ID Token and makes an API call to the Groups Building Block to retrieve all Rokwire groups that the user is part of.

**Describe alternatives you've considered**
No other alternatives were considered at this time.  

**Additional context**

**Comment by bingzhang** [comment]
@sandeep-ps this should be done already.

**Comment by sandeep-ps** [comment]
This is currently implemented in the Events Building Block. This can method can be moved to the Auth Library if another Building Block needs to use to access the same information. Closing this issue.
