### ISSUE TITLE
[FEATURE] Load url variable from .env instead of hardcode

### ISSUE THREAD

**Issue by wenjzhu** [rokwire/rokwire-building-blocks-api#622]
**Is your feature request related to a problem? Please describe.**
The url in javascript of contribution catalog was hardcoded now, which might be an issue for the future. 

**Describe the solution you'd like**
Load the variable using .env file. 

**Describe alternatives you've considered**

**Additional context**

**Comment by sandeep-ps** [comment]
This is currently implemented. Closing.
