### ISSUE TITLE
Image upload api[BUG]

### ISSUE THREAD

**Issue by clint156** [rokwire/rokwire-building-blocks-api#729]
When I try to use the image api to upload images that are not associated with events, I get the following error:
"The underlying connection was closed: An unexpected error occurred on a send."

I am attempting to post to https://api.rokwire.illinois.edu/images-service/api/v1/. This is from a long time ago and the end point may have changed, but I couldn't find anything about the images service in the api documentation either. Does the images service api still exist, if so, where do I find the documentation?

This is not really a bug, I don't guess, but I have been unable to find the answer on my own.

**Comment by sandeep-ps** [comment]
@clint156, please see the documentation here: https://github.com/rokwire/images-service. It looks like the endpoint is: POST /images-service/api/v1/image

**Comment by sandeep-ps** [comment]
Closing this as this was resolved. Please reopen if needed. Thanks.
