### ISSUE TITLE
[TASK] Go through App config building block

### ISSUE THREAD

**Issue by minump** [rokwire/rokwire-building-blocks-api#749]
### Description
Run appconfig API in local
 

### Acceptance Criteria
Run appconfig building block in local, with and without docker.
Get responses for all API endpoints using Postman

**Comment by minump** [comment]
Cryptography 3.3.2 not supported by M1 apply silicon BigSur.
Cryptography version 3.4.7 installed without error. Changed requirements.txt to reflect cryptography==3.4.7

**Comment by minump** [comment]
POST API endpoint getting 401 response.
Running using Docker - GET taking too long to respond.

**Comment by sandeep-ps** [comment]
I think you have completed this, right? If so, please close the issue. Thanks.

**Comment by minump** [comment]
Completed
