### ISSUE TITLE
[HOTFIX]  temporarily turn off the group authentication on images search and get endpoints.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/rokwire-building-blocks-api#750]
### Description
temporarily turn off the group authentication on images endpoints.

### Acceptance Criteria
_Please describe what it means for this issue to be considered complete._

**Comment by sandeep-ps** [comment]
This was changed only in the image GET by ID endpoint as the other endpoint doesn't seem to be getting used by the client now.
