### ISSUE TITLE
[TASK] Create Flask webapp

### ISSUE THREAD

**Issue by minump** [rokwire/rokwire-building-blocks-api#752]
### Description
Go through flask tutorial https://flask.palletsprojects.com/en/2.0.x/tutorial/index.html and create a webapp

### Acceptance Criteria
_Please describe what it means for this issue to be considered complete._

**Comment by minump** [comment]
Created webapp with SQLite.
Blueprint, views and Auth pending.

**Comment by sandeep-ps** [comment]
If you have completed the tutorial, please close this issue. Thanks.

**Comment by minump** [comment]
Completed tutorial
