### ISSUE TITLE
[FEATURE] Add GET /ok endpoint to App Config Building Block

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/rokwire-building-blocks-api#754]
**Is your feature request related to a problem? Please describe.**
Currently, we do not have a health check endpoint that returns HTTP 200. We need this for better health checks using AWS.

**Describe the solution you'd like**
1. Please add a GET /ok endpoint that returns HTTP 200 with JSON ```{"success": "true"}```.

**Describe alternatives you've considered**

**Additional context**

**Comment by minump** [comment]
api/controllers/app.py

def config_ok():
    # ok endpoint for healthcheck
    # no need for args and auth.
    # might need to make some changes in resolver to route to this endpoint.
    # ping someother endpoint - for example get and check if it is the desired response - using try except
    # if correct response, return success_response(200, msg, id) where msg={'success':'true'} , not sure what id have to be
    # put msg in logger __logger,info(msg)
    # if not correct response, abort with 404=page not found response
    # can also do via assert statement -- assert response.status_code=200 
    pass

**Comment by sandeep-ps** [comment]
This endpoint needs to return HTTP 200 always. It should not ping other endpoints. You won't have to make any changes to the resolver. It should work as it is. The response JSON data is ```{"success":'"true"}```. There is no ID to return.

**Comment by minump** [comment]
![Screen Shot 2021-08-18 at 1 34 23 PM](https://user-images.githubusercontent.com/22112888/129953454-c90141c5-b416-4e40-8a4d-f54ad98b02b8.png)

**Comment by minump** [comment]
![Screen Shot 2021-08-18 at 1 37 06 PM](https://user-images.githubusercontent.com/22112888/129953601-f30abb4c-d80b-4d8d-8627-2c5700bbd96b.png)

Is this the required output?

**Comment by sandeep-ps** [comment]
The below response should be fine. I don't think we need other details. The client can get status 200 from the response status. 

```
{
"success": true
}
```

Here the value is boolean.

**Comment by minump** [comment]
@sandeep-ps Should it work without Authorization? Or should it have ROKWIRE-API-KEY auth?

**Comment by sandeep-ps** [comment]
It should work without authorization. It's a public end point.

**Comment by minump** [comment]
@sandeep-ps localhost:5000://app/configs/ok behaves like localhost:5000://app/configs/{id} and gets routed to def configs_get(id) rather than the new function. Not sure on how to resolve this.

**Comment by sandeep-ps** [comment]
I think you need a function called configs_ok_search since this doesn't have an ID.

search -> GET
get -> GET by ID

**Comment by minump** [comment]
Created a new function config_ok_search() which returns {'success':'true'}. Created a new path /app/configs/ok in yaml file get method without security. Running the modified app/config using python and checking the response via POSTMAN, it returns the required response.

**Comment by sandeep-ps** [comment]
Great! Please create a pull request by following the instructions here: https://github.com/rokwire/rokwire-building-blocks-api/blob/develop/CONTRIBUTING.md#development-workflow. You can create a branch in this repository rather than creating a fork. Please let me know if you have any questions.

**Comment by sandeep-ps** [comment]
Added this issue to Sprint 42.
