### ISSUE TITLE
[FEATURE] Add /version endpoint to AppConfig Building Block

### ISSUE THREAD

**Issue by minump** [rokwire/rokwire-building-blocks-api#760]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have a way to retrieve the Building Block's version number through API.

**Describe the solution you'd like**
We need to add a /version endpoint that returns the current version number. OpenAPI specification YAML file needs to be updated with this endpoint. Basically, the building block needs to capture its docker image tag and return that in the response. Response Content-Type can be text/plain. If reading the docker image tag from within the container is not straightforward, the building block can read the version number in the YAML file.

**Additional context**
Epic: #738

**Comment by minump** [comment]
Added configs_version_search method which reads the appconfig yaml file and returns the version number. Added the path to yaml file. http://localhost:5000/app/configs/version returns the version in plain text format.

**Comment by sandeep-ps** [comment]
Hi, Minu, Yes, this looks fine. Please make sure that the response Content-Type is text/plain. Thanks.
