### ISSUE TITLE
[FEATURE] Add footer to Contributions Catalog

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/rokwire-building-blocks-api#770]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have a footer in the Contributions Catalog.

**Describe the solution you'd like**
Please add a footer to the Contributions Catalog. This could be implemented using a base layout. The following details that are separated by a vertical bar (`|`) need to be added to the footer :

1. Catalog version number (e.g., v1.10.11). This can be obtained by parsing the latest git release tag. 
2. © <current year> University of Illinois Board of Trustees
2. Privacy Policy that links to https://www.vpaa.uillinois.edu/resources/web_privacy

**Describe alternatives you've considered**

**Additional context**

**Comment by minump** [comment]
just reading this I understand that this is adding another template that extends the base.html. Let me know if my understanding is correct. 
Would also like to know if this is to be displayed for all the webpages/templates in Catalog.

**Comment by sandeep-ps** [comment]
If possible, please try to update the base.html to include the footer. Yes, the idea is that this footer will appear on every page.

**Comment by minump** [comment]
Updated home.html to include footer. This works as intended. 
Update base.html to include footer. Extended base.html in home.html. This results in only the footer being rendered. None of the contents in home.html is being rendered in this method.

**Comment by minump** [comment]
Issue description has been changed to include footer in home.html.
