### ISSUE TITLE
[BUG] "Hello!" appearing in the title bar when the user is not logged in

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/rokwire-building-blocks-api#779]
**Describe the bug**
This might be the result of not using the base.html throughout the application.

**To Reproduce**
1. Go to the Catalog home page.
2. Do not log in.
3. Click on a published Capability of Talent to view the details.
4. See "Hello!" and the icon in the title bar.

**Expected behavior**
The login button should appear on all the pages when the user is not logged in.

**Screenshots**
![image](https://user-images.githubusercontent.com/4306604/131688675-11552d9d-18d9-4bfc-8cc8-9f937ca89b79.png)

**Additional context**
This might be caused due to not using the base.html on all pages.

**Comment by ywkim312** [comment]
This is a duplicate issue as 773

**Comment by sandeep-ps** [comment]
Thanks. When you work on that task, please make sure that the login button will appear on all pages when the user is not logged in. I will close this. Thanks.

Duplicate of #773
