### ISSUE TITLE
[FEATURE] Send email notifications to reviewers.

### ISSUE THREAD

**Issue by minump** [rokwire/rokwire-building-blocks-api#839]
### Description
Send email notifications to reviewers when new a reviewer is added to the system. 
Create a method to send an email notification. This method can then be used to notify the reviewers when a new Contribution gets added.
This feature is part of #397 , Key Feature number 9.

### Acceptance Criteria
Reviewers get an email notification.

**Comment by sandeep-ps** [comment]
Hi, @minump, please move this to the Events Manager repo. Thanks.

**Comment by sandeep-ps** [comment]
I have updated the title to avoid my future confusion! :-)

**Comment by minump** [comment]
Changing the scope to add reviewers email id in reviewer collection and send email via SMTP servers.

**Comment by sandeep-ps** [comment]
We can need to send notifications to reviewers when a Contribution gets added to the system. 

We need to look at sending notifications for the below items after some discussion:
1. Reviewing
2. Approved
3. Disapproved
4. Publishing
