### ISSUE TITLE
[TASK] Establish SMTP connection once and use the same connection for all email notifications

### ISSUE THREAD

**Issue by minump** [rokwire/rokwire-building-blocks-api#901]
### Description
Currently email notification for new contributions and new reviewers establishes new SMTP connection each time in adminutils.send_email() method. The SMTP connection is established during POST request which increases the time to POST. Change this to have one SMTP connection that could then be utilized for all email notification functionalities. 
Make sure that the connection is active before sendmail() method is called.
### Acceptance Criteria
SMTP connection (with login) established once and used for all notifications.

**Comment by sandeep-ps** [comment]
Closing as PR was closed.
