### ISSUE TITLE
[TASK] add required building block in contribution and end point

### ISSUE THREAD

**Issue by ywkim312** [rokwire/rokwire-building-blocks-api#904]
### Description
Please update the list of available building blocks in Contributions BB to include these:

Admin
App Config
Content
Core
Events
Groups
Learning Management System
Locations
Logs
Notifications
Polls
Rewards
Sports
Talent Chooser
Transportation

### Acceptance Criteria
The required building blocks list is updated.

**Comment by ywkim312** [comment]
Is it okay if I make above selections only in catalog's code? Or should I also add this values to yaml as well? If we add this to yaml as well, it will be good that yaml will make an error when the weird values comes in, but when we need to edit the list, we have to edit both code and yaml. I think that if we make this list as full down in the code, we probably don't need to add these values to yaml... ? What do you think?

**Comment by sandeep-ps** [comment]
I will get back in 30 mins or something like that. I was thinking to update the BB first. Thanks.

**Comment by ywkim312** [comment]
This will be implemented using the separated json file that contains the list of the building blocks. Also, the endpoint for showing the list of building blocks using the Json file should be added in this issue.
