### ISSUE TITLE
[FEATURE] Delete button for contribution

### ISSUE THREAD

**Issue by minump** [rokwire/rokwire-building-blocks-api#944]
### Description
Implement a delete button for the entire contribution. When user clicks on delete button, show a pop-up that all capabilities and talents related to the contribution will also be deleted. The delete button should be re-directed to the end point {{baseUrl}}/contributions/{{contributionId}}

### Acceptance Criteria
On clicking delete button, and confirming the same in pop-up, the contribution is deleted from monoDB collection.

**Comment by sandeep-ps** [comment]
Since this is a feature, please use [FEATURE] in the title. Thanks.
