### ISSUE TITLE
[FEATURE] Allow all group admins to manage group events

### ISSUE THREAD

**Issue by shurwit** [rokwire/rokwire-building-blocks-api#996]
**Is your feature request related to a problem? Please describe.**
Currently users need to have specific permissions to create a new event in the Events BB. To support group events, we will need to allow any group admin to do so.

**Describe the solution you'd like**
When a request to create a new group event is received and the user does not have the appropriate permissions, we should also check to see if they are the admin of the specified group. If they are, we should allow them to continue. The same process should apply to update and delete group events. 

**Describe alternatives you've considered**
An alternative would be to assign all group admins that will be uploading events the appropriate permissions to do so. This will take a significant amount of manual effort and does not match the current UI which makes it look like any group admin can create an event.

**Additional context**
This was reported by RAs attempting to create events for their residence hall groups.

**Comment by sandeep-ps** [comment]
When a user changes an event's group, they need to be an admin of the old and new groups. @shurwit, does this sound right?

**Comment by shurwit** [comment]
> When a user changes an event's group, they need to be an admin of the old and new groups. @shurwit, does this sound right?

Hi @sandeep-ps, yes that sounds right to me. Thanks!
