### ISSUE TITLE
[BUG] Docker build failure events bb

### ISSUE THREAD

**Issue by bingzhang** [rokwire/rokwire-building-blocks-api#999]
src/gevent/greenlet.py because it changed.
#12 75.52       [1/1] Cythonizing src/gevent/greenlet.py
#12 75.52       Traceback (most recent call last):
#12 75.52         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#12 75.52           main()
#12 75.52         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#12 75.52           json_out['return_val'] = hook(**hook_input['kwargs'])
#12 75.52         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#12 75.52           return hook(config_settings)
#12 75.52         File "/tmp/pip-build-env-i6e6nb1n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
#12 75.52           return self._get_build_requires(config_settings, requirements=['wheel'])
#12 75.52         File "/tmp/pip-build-env-i6e6nb1n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
#12 75.52           self.run_setup()
#12 75.52         File "/tmp/pip-build-env-i6e6nb1n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 482, in run_setup
#12 75.52           super(_BuildMetaLegacyBackend,
#12 75.52         File "/tmp/pip-build-env-i6e6nb1n/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
#12 75.52           exec(code, locals())
#12 75.52         File "<string>", line 287, in <module>
#12 75.52         File "/tmp/pip-install-waenupif/gevent_cb6b5ca000724bb8acd0ecb03c93ab4b/_setuputils.py", line 236, in cythonize1
#12 75.52           new_ext = cythonize(
#12 75.52         File "/tmp/pip-build-env-i6e6nb1n/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1129, in cythonize
#12 75.52           cythonize_one(*args)
#12 75.52         File "/tmp/pip-build-env-i6e6nb1n/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1296, in cythonize_one
#12 75.52           raise CompileError(None, pyx_file)
#12 75.52       Cython.Compiler.Errors.CompileError: src/gevent/greenlet.py
#12 75.52       [end of output]
#12 75.52   
#12 75.52   note: This error originates from a subprocess, and is likely not a problem with pip.
#12 75.52 error: subprocess-exited-with-error
#12 75.52 
#12 75.52 × Getting requirements to build wheel did not run successfully.
#12 75.52 │ exit code: 1
#12 75.52 ╰─> See above for output.
#12 75.52 
#12 75.52 note: This error originates from a subprocess, and is likely not a problem with pip.
------
executor failed running [/bin/sh -c apk --update add python3 py3-pip openssl ca-certificates py3-openssl &&   apk --update add --virtual build-dependencies libffi-dev openssl-dev python3-dev py3-pip musl-dev cargo build-base &&   pip install --upgrade pip &&   pip install -r /app/eventservice/requirements.txt --no-cache-dir &&   apk del build-dependencies]: exit co

**Comment by sandeep-ps** [comment]
Closing as complete.
